### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by D22NK** [RoganDawes/P4wnP1#265]
I install this following the install.md but when i rebooted it did not come back on. The wifi network also does not show up. 
How can i fix this?

**Comment by Swiftb0y** [comment]
Try the pre-built raspbian image.

**Comment by D22NK** [comment]
how do i do that?

**Comment by Swiftb0y** [comment]
Look at the first three paragraphs of the Readme and use dd or Rufus (depending on your OS) to flash the image to the SD-Card.

**Comment by D22NK** [comment]
i am gonna try. Thanks for helping

**Comment by Swiftb0y** [comment]
Do you have an adapter to Plug the Pi0W into a display?

**Comment by D22NK** [comment]
Yes

**Comment by D22NK** [comment]
Thanks for the help but is working now. i was using the ip 172.16.0.1 but i have to use 172.24.0.1

**Comment by Swiftb0y** [comment]
Yes. The Pi will be reachable via 172.16.0.1 when connecting to it with a cable and 172.24.0.1 when connecting via wifi. But these are default values which can be changed within the payload/setup.cfg file.
