### ISSUE TITLE
P4wnP1 Stuck On Rainbow Splash Screen

### ISSUE THREAD

**Issue by Puffball101961** [RoganDawes/P4wnP1#274]
Hello,
I recently followed the installation instructions on the docs, and after I reboot the raspberry pi it is stuck on the splash screen.

Please Help

**Comment by Swiftb0y** [comment]
The installation instructions in the Docs might be outdated... (I haven't looked at them in a while). I suggest you try the pre-built raspbian image which raspbian already installed. You can find a link to it in the README.md

> Important
This repo isn't really suspended, but I'm using all of my time to work on P4wnP1's successor. The new Repo is still private, but information on progress are published via twitter, from time to time (@P4wnP1 or @MaMe82).
More important: Don't waste your time following complicated install instructions: A ready-to-go image of latest P4wnP1 version could be found on the release page: https://github.com/mame82/P4wnP1/releases (seems some of you missed it).

**Comment by al7aker** [comment]
don't plug the power just plug USB.
